# Generated by Django 6.0.2 on 2026-03-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_recipeimage_recipe_key_recipeimage_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
